import SideBar from "@/components/profile/side-bar";
import type { Metadata } from "next";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <div className='flex-1 grid grid-cols-[300px_1fr_300px] gap-10 bg-secondary'>
      <SideBar />
      <div className="flex-1 flex items-center justify-center">
        {children}
      </div>
    </div>

  );
}
