import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import SessionProvider from "@/lib/SessionProvider";
import { ThemeProvider } from "@/components/theme-provider";


const geistSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.className}  antialiased`}
      >
        <SessionProvider>
        <ThemeProvider
    attribute="class"
    defaultTheme="system"
    enableSystem
    disableTransitionOnChange
  >
            {children}
            </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  

  );
}
